apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  selector:
    matchLabels:
      app: springboot-app
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springapp
          image: kskml/springboot-app:d5c2aadabee30ba2dc4bf4856e6023ad44a62ab0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
