apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  selector:
    matchLabels:
      app: springboot-app
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springapp
          image: kskml/springboot-app:7f6b604c3e7ce0db1d78e404c9bd07776b15881c
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
