apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  selector:
    matchLabels:
      app: springboot-app
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springapp
          image: kskml/springboot-app:75c7898c8a977a7547759c65cf4d6f5f7abe3679
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
