apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  selector:
    matchLabels:
      app: springboot-app
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springapp
          image: kskml/springboot-app:146fcd29d16b5c2d1e83dbff4b9f4c485d0d56c3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
