apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  selector:
    matchLabels:
      app: springboot-app
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springapp
          image: kskml/springboot-app:3ec47adc7ed8c809d359e511de65c30a764a5626
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
