name: Spring Boot CI/CD

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  set-tag:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.timestamp.outputs.image_tag }}
    steps:
      - name: Generate timestamp tag
        id: timestamp
        run: |
          echo "image_tag=$(date +%Y%m%d-%H%M%S)" >> "$GITHUB_OUTPUT"

  build-and-push:
    runs-on: ubuntu-latest
    needs: set-tag
    env:
      IMAGE_TAG: ${{ needs.set-tag.outputs.image-tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with timestamp tag
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ env.IMAGE_TAG }}

  update_k8s_manifests:
    runs-on: ubuntu-latest
    needs: [set-tag, build-and-push]
    env:
      IMAGE_TAG: ${{ needs.set-tag.outputs.image-tag }}
    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v3
        with:
          repository: kskml/boot-k8s-argocd
          token: ${{ secrets.GH_TOKEN }}
          path: gitops

      - name: Update Deployment.yaml with new image tag
        run: |
          sed -i "s|image: kskml/springboot-app:.*|image: kskml/springboot-app:$IMAGE_TAG|" gitops/k8s/deployment.yaml

      - name: Commit and push changes
        run: |
          cd gitops
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add k8s/deployment.yaml
          git commit -m "Update image tag to $IMAGE_TAG [skip ci]"
          git push
